#### Setup necessary libraries

In [2]:
%pip install numpy pandas matplotlib seaborn scikit-learn -q

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

#### Step 0: Imports and reading data

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
pd.set_option('display.max_columns', 200)

In [4]:
df = pd.read_csv('Roller Coaster Dataset/coaster_db.csv')

#### Step 1: Data Understanding

            1. dataframe (shape)
            2. head and tail
            3. dtypes
            4. describe

In [5]:
df.shape

(1087, 56)

In [6]:
df.head()

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,Height,Inversions,Lift/launch system,Cost,Trains,Park section,Duration,Capacity,G-force,Designer,Max vertical angle,Drop,Soft opening date,Fast Lane available,Replaced,Track layout,Fastrack available,Soft opening date.1,Closing date,Opened,Replaced by,Website,Flash Pass Available,Must transfer from wheelchair,Theme,Single rider line available,Restraint Style,Flash Pass available,Acceleration,Restraints,Name,year_introduced,latitude,longitude,Type_Main,opening_date_clean,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,50 ft (15 m),NaN,gravity,NaN,NaN,Coney Island Cyclone Site,1:00,1600 riders per hour,2.9,LaMarcus Adna Thompson,30°,43 ft (13 m),NaN,NaN,NaN,Gravity pulled coaster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1884,40.5740,-73.9780,Wood,1884-06-16,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,NaN,1.0,NaN,NaN,a single car. Riders are arranged 1 across in ...,NaN,NaN,NaN,12,Lina Beecher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1896,41.5800,-81.5700,Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,NaN,1.0,NaN,NaN,a single car. Riders are arranged 2 across in ...,NaN,NaN,NaN,NaN,Edward A. Green,NaN,NaN,NaN,NaN,Switchback Railway,NaN,NaN,NaN,1910,NaN,Giant Racer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Edward A. Green,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

In [7]:
df.columns

Index(['coaster_name', 'Length', 'Speed', 'Location', 'Status', 'Opening date',
       'Type', 'Manufacturer', 'Height restriction', 'Model', 'Height',
       'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       'Track layout', 'Fastrack available', 'Soft opening date.1',
       'Closing date', 'Opened', 'Replaced by', 'Website',
       'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       'Single rider line available', 'Restraint Style',
       'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 'height_value', 'height_unit', 'height_ft',
       'Inversions_clean', 'Gforce_clean'],
      dtype='str')

In [8]:
df.dtypes

coaster_name                         str
Length                               str
Speed                                str
Location                             str
Status                               str
Opening date                         str
Type                                 str
Manufacturer                         str
Height restriction                   str
Model                                str
Height                               str
Inversions                       float64
Lift/launch system                   str
Cost                                 str
Trains                               str
Park section                         str
Duration                             str
Capacity                             str
G-force                              str
Designer                             str
Max vertical angle                   str
Drop                                 str
Soft opening date                    str
Fast Lane available                  str
Replaced                             str
Track layout                         str
Fastrack available                   str
Soft opening date.1                  str
Closing date                         str
Opened                               str
Replaced by                          str
Website                              str
Flash Pass Available                 str
Must transfer from wheelchair        str
Theme                                str
Single rider line available          str
Restraint Style                      str
Flash Pass available                 str
Acceleration                         str
Restraints                           str
Name                                 str
year_introduced                    int64
latitude                         float64
longitude                        float64
Type_Main                            str
opening_date_clean                   str
speed1                               str
speed2                               str
speed1_value                     float64
speed1_unit                          str
speed_mph                        float64
height_value                     float64
height_unit                          str
height_ft                        float64
Inversions_clean                   int64
Gforce_clean                     float64
dtype: object

In [9]:
df.describe()

,Inversions,year_introduced,latitude,longitude,speed1_value,speed_mph,height_value,height_ft,Inversions_clean,Gforce_clean
count,932.000000,1087.000000,812.000000,812.000000,937.000000,937.000000,965.000000,171.000000,1087.000000,362.000000
mean,1.547210,1994.986201,38.373484,-41.595373,53.850374,48.617289,89.575171,101.996491,1.326587,3.824006
std,2.114073,23.475248,15.516596,72.285227,23.385518,16.678031,136.246444,67.329092,2.030854,0.989998
min,0.000000,1884.000000,-48.261700,-123.035700,5.000000,5.000000,4.000000,13.100000,0.000000,0.800000
25%,0.000000,1989.000000,35.031050,-84.552200,40.000000,37.300000,44.000000,51.800000,0.000000,3.400000
50%,0.000000,2000.000000,40.289800,-76.653600,50.000000,49.700000,79.000000,91.200000,0.000000,4.000000
75%,3.000000,2010.000000,44.799600,2.778100,63.000000,58.000000,113.000000,131.200000,2.000000,4.500000
max,14.000000,2022.000000,63.230900,153.426500,240.000000,149.100000,3937.000000,377.300000,14.000000,12.000000

#### Step 2: Data Preperation

            1. Dropping irrelevant columns and rows
            2. Changing Data Types of the Columns
            3. Rename the column names
            4. Identifying Duplicated Columns
            5. Feature Creation

2.1 Dropping irrelevant columns and rows

In [10]:
# Example of dropping columns
# df.drop(['Opening date'], axis=1)

In [11]:
# # Example of dropping multiple rows
# df1 = df1.drop(index=[0, 1, 2])

In [12]:
df1 = df[['coaster_name', 
    #'Length', 'Speed', 
    'Location', 'Status', 
    #'Opening date','Type', 
       'Manufacturer', 
       # 'Height restriction', 'Model', 'Height',
       #'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       #'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       #'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       #'Track layout', 'Fastrack available', 'Soft opening date.1',
       #'Closing date', 'Opened', 'Replaced by', 'Website',
       #'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       #'Single rider line available', 'Restraint Style',
       #'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 
       'latitude', 
       'longitude', 
       'Type_Main',
       'opening_date_clean', 
       #'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 
       #'height_value', 'height_unit', 
       'height_ft',
       'Inversions_clean', 'Gforce_clean']].copy()

In [13]:
df1.shape

(1087, 13)

In [14]:
df1.dtypes

coaster_name              str
Location                  str
Status                    str
Manufacturer              str
year_introduced         int64
latitude              float64
longitude             float64
Type_Main                 str
opening_date_clean        str
speed_mph             float64
height_ft             float64
Inversions_clean        int64
Gforce_clean          float64
dtype: object

2.2 Change the data type of the column

In [15]:
df1['opening_date_clean'] = pd.to_datetime(df1['opening_date_clean'])

2.3 Rename the column names

In [16]:
df1.columns

Index(['coaster_name', 'Location', 'Status', 'Manufacturer', 'year_introduced',
       'latitude', 'longitude', 'Type_Main', 'opening_date_clean', 'speed_mph',
       'height_ft', 'Inversions_clean', 'Gforce_clean'],
      dtype='str')

In [17]:
df2 = df1.rename(columns={'coaster_name': 'Coaster_Name',
                    'year_introduced': 'Year Introduced',
                    'latitude': 'Latitude',
                    'longitude': 'Longitude',
                    'opening_date_clean': 'Opening Date',
                    'speed_mph': 'Speed-Mph',
                    'height_ft': 'Height-Ft'})

In [18]:
df2.columns

Index(['Coaster_Name', 'Location', 'Status', 'Manufacturer', 'Year Introduced',
       'Latitude', 'Longitude', 'Type_Main', 'Opening Date', 'Speed-Mph',
       'Height-Ft', 'Inversions_clean', 'Gforce_clean'],
      dtype='str')

In [19]:
df2.head()

,Coaster_Name,Location,Status,Manufacturer,Year Introduced,Latitude,Longitude,Type_Main,Opening Date,Speed-Mph,Height-Ft,Inversions_clean,Gforce_clean
0,Switchback Railway,Coney Island,Removed,LaMarcus Adna Thompson,1884,40.5740,-73.9780,Wood,1884-06-16,6.0,NaN,0,2.9
1,Flip Flap Railway,Sea Lion Park,Removed,Lina Beecher,1895,40.5780,-73.9790,Wood,1895-01-01,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),"Cleveland, Ohio, United States",Closed,NaN,1896,41.5800,-81.5700,Other,NaT,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),Other,Removed,Edwin Prescott,1901,40.5745,-73.9780,Steel,1901-01-01,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),Other,Removed,Edwin Prescott,1901,39.3538,-74.4342,Steel,1901-01-01,NaN,NaN,1,NaN

2.4 Find missing/null values

In [22]:
df2.isna()

,Coaster_Name,Location,Status,Manufacturer,Year Introduced,Latitude,Longitude,Type_Main,Opening Date,Speed-Mph,Height-Ft,Inversions_clean,Gforce_clean
0,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,True,True,False,False
2,False,False,False,True,False,False,False,False,True,True,True,False,True
3,False,False,False,False,False,False,False,False,False,True,True,False,True
4,False,False,False,False,False,False,False,False,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,False,False,True,False,False,True,True,False,True,False,True,False,False
1083,False,False,False,False,False,False,False,False,False,False,True,False,True
1084,False,False,True,False,False,True,True,False,False,False,True,False,False
1085,False,False,False,False,False,True,True,False,True,False,True,False,True
1086,False,False,False,False,False,True,True,False,False,False,True,False,True

In [23]:
df2.isna().sum()

Coaster_Name          0
Location              0
Status              213
Manufacturer         59
Year Introduced       0
Latitude            275
Longitude           275
Type_Main             0
Opening Date        250
Speed-Mph           150
Height-Ft           916
Inversions_clean      0
Gforce_clean        725
dtype: int64